export const VISIBILITY_SETIINGS = 'VISIBILITY_SETIINGS';
export const SET_QUANTITY_NEWS = 'SET_QUANTITY_NEWS';
export const IS_LOAD_IMAGES = 'IS_LOAD_IMAGES';
export const SET_ACTIVE_TAB_INDEX = 'SET_ACTIVE_TAB_INDEX';
export const SELECTED_NEWS_FOR_LOADING = 'SELECTED_NEWS_FOR_LOADING';